version: "3.9"

services:
    frontend:
        build:
            context: .
            dockerfile: ./Docker/frontend/Dockerfile
        volumes:
            - ./app/frontend/:/app/
        expose:
            - 80:80
    backend:
        build:
            context: .
            dockerfile: ./Docker/backend/Dockerfile
        volumes:
            - ./app/backend/:/app/
        expose:
            - 8000
