version: "3.9"

services:
    frontend:
        build:
            context: .
            dockerfile: Docker/frontend/Dockerfile
        volumes:
            - ./app/frontend/:/app/
            - ./log:/var/log/:rw
            - react-build:/app/build/
        env_file:
            - .env
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: Docker/backend/Dockerfile
        env_file:
            - .env
        volumes:
            - ./app/backend/:/app/
            - ./log:/var/log/:rw
        expose:
            - 8000

    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        volumes:
            - react-build:/usr/share/nginx/html/
            - ./log:/var/log/:rw
        depends_on:
            - frontend
volumes:
    react-build: