version: "3.9"

services:
    frontend:
        build:
            context: .
            dockerfile: Docker/frontend/Dockerfile
        volumes:
            - ./app/frontend/:/app/
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        build:
            context: .
            dockerfile: Docker/backend/Dockerfile
        env_file:
            - .env
        volumes:
            - ./app/backend/:/app/
        ports:
            - 8000:8000

