name: React testing

on: [push]

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/frontend/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test
