name: React testing

on: [push]

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      working-directory: ./app/frontend/


    - name: Run Jest tests
      run: npm test
      working-directory: ./app/frontend/
