name: React testing

on: [push]

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/frontend/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests and calculate coverage
      run: npm test -- --coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
